# Generated by Django 5.1.15 on 2026-09-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, help_text='Fiche annuaire du titulaire. Nulle pour un compte de support.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='directory.member'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Nul pour un compte de support, qui n'appartient à aucun labo.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.organization'),
        ),
    ]
