# Generated by Django 5.1.15 on 2026-09-02 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, help_text='Fiche annuaire du titulaire. Nulle pour un compte de support.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='directory.member'),
        ),
    ]
