# Generated by Django 5.1.15 on 2026-09-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_member'),
        ('actions', '0001_initial'),
        ('common', '0001_initial'),
        ('directory', '0002_formation_partnerlab'),
        ('finance', '0002_financialagreement_agreementmember_budgetcategory_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementactioncard',
            name='financial_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_card_links', to='finance.financialagreement'),
        ),
        migrations.AddField(
            model_name='agreementactioncard',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='axisactioncard',
            name='action_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_links', to='actions.actioncard'),
        ),
        migrations.AddField(
            model_name='axisactioncard',
            name='axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_card_links', to='projects.axis'),
        ),
        migrations.AddField(
            model_name='axisactioncard',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='actions.category'),
        ),
        migrations.AddField(
            model_name='actioncard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_cards', to='actions.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='action_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='actions.actioncard'),
        ),
        migrations.AddField(
            model_name='comment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='directory.member'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='actions.comment'),
        ),
        migrations.AddField(
            model_name='memberactioncard',
            name='action_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='actions.actioncard'),
        ),
        migrations.AddField(
            model_name='memberactioncard',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_card_links', to='directory.member'),
        ),
        migrations.AddField(
            model_name='memberactioncard',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='memberactioncard',
            name='participation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_card_participations', to='common.status'),
        ),
        migrations.AddField(
            model_name='projectactioncard',
            name='action_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='actions.actioncard'),
        ),
        migrations.AddField(
            model_name='projectactioncard',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
    ]
