# Generated by Django 5.1.15 on 2026-09-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_member'),
        ('actions', '0002_initial'),
        ('common', '0001_initial'),
        ('projects', '0002_alter_group_owner_kpi_mobilitygrant_phd_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactioncard',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_card_links', to='projects.project'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_items', to='common.status'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='action_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to='actions.actioncard'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='actions.todolist'),
        ),
        migrations.AddConstraint(
            model_name='agreementactioncard',
            constraint=models.UniqueConstraint(fields=('action_card', 'financial_agreement'), name='uniq_agreement_action_card'),
        ),
        migrations.AddConstraint(
            model_name='axisactioncard',
            constraint=models.UniqueConstraint(fields=('action_card', 'axis'), name='uniq_axis_action_card'),
        ),
        migrations.AddConstraint(
            model_name='memberactioncard',
            constraint=models.UniqueConstraint(fields=('action_card', 'member'), name='uniq_member_action_card'),
        ),
        migrations.AddConstraint(
            model_name='projectactioncard',
            constraint=models.UniqueConstraint(fields=('action_card', 'project'), name='uniq_project_action_card'),
        ),
    ]
