# Generated by Django 5.1.15 on 2026-09-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_member'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('type', models.CharField(blank=True, default='', max_length=40)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('level', models.CharField(blank=True, default='', max_length=200)),
                ('degree_type', models.CharField(blank=True, default='', max_length=200)),
                ('formacode', models.CharField(blank=True, default='', max_length=200)),
                ('rome', models.CharField(blank=True, default='', max_length=200)),
                ('nsf', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(blank=True, default='', max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_national', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='directory.partner')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='directory.lab')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_links', to='directory.partner')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('partner', 'lab'), name='uniq_lab_partner')],
            },
        ),
    ]
