# Generated by Django 5.1.15 on 2026-09-02 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('siret', models.CharField(blank=True, default='', max_length=20)),
                ('sifac_code', models.CharField(blank=True, default='', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sifac_code__gt', '')), fields=('organization', 'sifac_code'), name='uniq_supplier_sifac_code_per_org')],
            },
        ),
    ]
