# Generated by Django 5.1.15 on 2026-09-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_member'),
        ('directory', '0002_formation_partnerlab'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('signed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-signed_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AgreementMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_links', to='directory.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_categories', to='directory.partner')),
            ],
            options={
                'verbose_name_plural': 'budget categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BudgetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance.budgetcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.budgetdetail')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Expanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('flux_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('sifac', 'SIFAC'), ('manual', 'Saisie manuelle')], default='manual', max_length=10)),
                ('amount_engaged', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expanses', to='finance.budgetdetail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-purchase_date', 'title'],
            },
        ),
    ]
