# Generated by Django 5.1.15 on 2026-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expanse',
            name='uniq_expanse_flux_per_org',
        ),
        migrations.AddConstraint(
            model_name='expanse',
            constraint=models.UniqueConstraint(condition=models.Q(('flux_id__isnull', False)), fields=('program', 'flux_id'), name='uniq_expanse_flux_per_program'),
        ),
    ]
