# Generated by Django 5.1.15 on 2026-09-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_member'),
        ('common', '0001_initial'),
        ('directory', '0002_formation_partnerlab'),
        ('finance', '0002_financialagreement_agreementmember_budgetcategory_and_more'),
        ('projects', '0002_alter_group_owner_kpi_mobilitygrant_phd_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expanse',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expanses', to='projects.project'),
        ),
        migrations.AddField(
            model_name='expanse',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expanses', to='finance.supplier'),
        ),
        migrations.AddField(
            model_name='financialagreement',
            name='axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='projects.axis'),
        ),
        migrations.AddField(
            model_name='financialagreement',
            name='budget_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='finance.budgetdetail'),
        ),
        migrations.AddField(
            model_name='financialagreement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='financialagreement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='directory.partner'),
        ),
        migrations.AddField(
            model_name='financialagreement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='projects.project'),
        ),
        migrations.AddField(
            model_name='financialagreement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='common.status'),
        ),
        migrations.AddField(
            model_name='expanse',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expanses', to='finance.financialagreement'),
        ),
        migrations.AddField(
            model_name='agreementmember',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='finance.financialagreement'),
        ),
        migrations.AddConstraint(
            model_name='expanse',
            constraint=models.UniqueConstraint(condition=models.Q(('flux_id__isnull', False)), fields=('organization', 'flux_id'), name='uniq_expanse_flux_per_org'),
        ),
        migrations.AddConstraint(
            model_name='agreementmember',
            constraint=models.UniqueConstraint(fields=('agreement', 'member'), name='uniq_agreement_member'),
        ),
    ]
