# Generated by Django 5.1.15 on 2026-09-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expanse_project_expanse_supplier_and_more'),
        ('projects', '0002_alter_group_owner_kpi_mobilitygrant_phd_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialagreement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='projects.project'),
        ),
    ]
