# Generated by Django 5.1.15 on 2026-09-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'constraints': [models.UniqueConstraint(fields=('organization', 'label', 'context'), name='uniq_status_per_org')],
            },
        ),
    ]
