# Generated by Django 5.1.15 on 2026-09-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SifacLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfi', models.CharField(blank=True, default='', max_length=50)),
                ('exercice', models.IntegerField(default=0)),
                ('flux_id', models.CharField(blank=True, default='', max_length=50)),
                ('flux_label', models.CharField(blank=True, default='', max_length=255)),
                ('rubrique', models.CharField(blank=True, default='', max_length=100)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=50)),
                ('account', models.CharField(blank=True, default='', max_length=50)),
                ('account_label', models.CharField(blank=True, default='', max_length=255)),
                ('engagement_date', models.DateField(blank=True, null=True)),
                ('csf_date', models.DateField(blank=True, null=True)),
                ('amount_engaged', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_certified', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_text', models.TextField(blank=True, default='')),
                ('amount_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount_report', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('otp', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.program')),
            ],
            options={
                'ordering': ['flux_id', 'id'],
                'indexes': [models.Index(fields=['program', 'exercice'], name='sifac_sifac_program_43df41_idx'), models.Index(fields=['program', 'flux_id'], name='sifac_sifac_program_a941b2_idx')],
            },
        ),
    ]
